import {
  tomato,
  tomatoA,
  tomatoDark,
  tomatoDarkA,
  red,
  redA,
  redDark,
  redDarkA,
  crimson,
  crimsonA,
  crimsonDark,
  crimsonDarkA,
  pink,
  pinkA,
  pinkDark,
  pinkDarkA,
  plum,
  plumA,
  plumDark,
  plumDarkA,
  purple,
  purpleA,
  purpleDark,
  purpleDarkA,
  violet,
  violetA,
  violetDark,
  violetDarkA,
  indigo,
  indigoA,
  indigoDark,
  indigoDarkA,
  blue,
  blueA,
  blueDark,
  blueDarkA,
  cyan,
  cyanA,
  cyanDark,
  cyanDarkA,
  teal,
  tealA,
  tealDark,
  tealDarkA,
  green,
  greenA,
  greenDark,
  greenDarkA,
  grass,
  grassA,
  grassDark,
  grassDarkA,
  orange,
  orangeA,
  orangeDark,
  orangeDarkA,
  brown,
  brownA,
  brownDark,
  brownDarkA,
  sky,
  skyA,
  skyDark,
  skyDarkA,
  mint,
  mintA,
  mintDark,
  mintDarkA,
  lime,
  limeA,
  limeDark,
  limeDarkA,
  yellow,
  yellowA,
  yellowDark,
  yellowDarkA,
  amber,
  amberA,
  amberDark,
  amberDarkA,
  gray,
  grayA,
  grayDark,
  grayDarkA,
  mauve,
  mauveA,
  mauveDark,
  mauveDarkA,
  slate,
  slateA,
  slateDark,
  slateDarkA,
  sage,
  sageA,
  sageDark,
  sageDarkA,
  olive,
  oliveA,
  oliveDark,
  oliveDarkA,
  sand,
  sandA,
  sandDark,
  sandDarkA,
  gold,
  goldA,
  goldDark,
  goldDarkA,
  bronze,
  bronzeA,
  bronzeDark,
  bronzeDarkA,
  whiteA,
  blackA
} from '@radix-ui/colors';

const lightColors = {
  ...tomato,
  ...tomatoA,
  ...red,
  ...redA,
  ...crimson,
  ...crimsonA,
  ...pink,
  ...pinkA,
  ...plum,
  ...plumA,
  ...purple,
  ...purpleA,
  ...violet,
  ...violetA,
  ...indigo,
  ...indigoA,
  ...blue,
  ...blueA,
  ...cyan,
  ...cyanA,
  ...teal,
  ...tealA,
  ...green,
  ...greenA,
  ...grass,
  ...grassA,
  ...orange,
  ...orangeA,
  ...brown,
  ...brownA,
  ...sky,
  ...skyA,
  ...mint,
  ...mintA,
  ...lime,
  ...limeA,
  ...yellow,
  ...yellowA,
  ...amber,
  ...amberA,
  ...gray,
  ...grayA,
  ...mauve,
  ...mauveA,
  ...slate,
  ...slateA,
  ...sage,
  ...sageA,
  ...olive,
  ...oliveA,
  ...sand,
  ...sandA,
  ...gold,
  ...goldA,
  ...bronze,
  ...bronzeA,
  ...whiteA,
  ...blackA
};

const darkColors = {
  ...tomatoDark,
  ...tomatoDarkA,
  ...redDark,
  ...redDarkA,
  ...crimsonDark,
  ...crimsonDarkA,
  ...pinkDark,
  ...pinkDarkA,
  ...plumDark,
  ...plumDarkA,
  ...purpleDark,
  ...purpleDarkA,
  ...violetDark,
  ...violetDarkA,
  ...indigoDark,
  ...indigoDarkA,
  ...blueDark,
  ...blueDarkA,
  ...cyanDark,
  ...cyanDarkA,
  ...tealDark,
  ...tealDarkA,
  ...greenDark,
  ...greenDarkA,
  ...grassDark,
  ...grassDarkA,
  ...orangeDark,
  ...orangeDarkA,
  ...brownDark,
  ...brownDarkA,
  ...skyDark,
  ...skyDarkA,
  ...mintDark,
  ...mintDarkA,
  ...limeDark,
  ...limeDarkA,
  ...yellowDark,
  ...yellowDarkA,
  ...amberDark,
  ...amberDarkA,
  ...grayDark,
  ...grayDarkA,
  ...mauveDark,
  ...mauveDarkA,
  ...slateDark,
  ...slateDarkA,
  ...sageDark,
  ...sageDarkA,
  ...oliveDark,
  ...oliveDarkA,
  ...sandDark,
  ...sandDarkA,
  ...goldDark,
  ...goldDarkA,
  ...bronzeDark,
  ...bronzeDarkA
};

export const COLORS = {
  light: {
    ...lightColors,
    transparent: 'transparent',
    white: '#FCFCFC',
    black: '#171717',
    appBg: '$cyanA1',
    text: '$slate11',
    textContrast: '$slate12',

    // Neutral
    neutral1: '$slate1',
    neutral2: '$slate2',
    neutral3: '$slate3',
    neutral4: '$slate4',
    neutral5: '$slate5',
    neutral6: '$slate6',
    neutral7: '$slate7',
    neutral8: '$slate8',
    neutral9: '$slate9',
    neutral10: '$slate10',
    neutral11: '$slate11',
    neutral12: '$slate12',
    // Neutral Alpha
    neutralA1: '$slateA1',
    neutralA2: '$slateA2',
    neutralA3: '$slateA3',
    neutralA4: '$slateA4',
    neutralA5: '$slateA5',
    neutralA6: '$slateA6',
    neutralA7: '$slateA7',
    neutralA8: '$slateA8',
    neutralA9: '$slateA9',
    neutralA10: '$slateA10',
    neutralA11: '$slateA11',
    neutralA12: '$slateA12',

    // Info
    info1: '$cyan1',
    info2: '$cyan2',
    info3: '$cyan3',
    info4: '$cyan4',
    info5: '$cyan5',
    info6: '$cyan6',
    info7: '$cyan7',
    info8: '$cyan8',
    info9: '$cyan9',
    info10: '$cyan10',
    info11: '$cyan11',
    info12: '$cyan12',
    // Info Alpha
    infoA1: '$cyanA1',
    infoA2: '$cyanA2',
    infoA3: '$cyanA3',
    infoA4: '$cyanA4',
    infoA5: '$cyanA5',
    infoA6: '$cyanA6',
    infoA7: '$cyanA7',
    infoA8: '$cyanA8',
    infoA9: '$cyanA9',
    infoA10: '$cyanA10',
    infoA11: '$cyanA11',
    infoA12: '$cyanA12',

    // Success
    success1: '$green1',
    success2: '$green2',
    success3: '$green3',
    success4: '$green4',
    success5: '$green5',
    success6: '$green6',
    success7: '$green7',
    success8: '$green8',
    success9: '$green9',
    success10: '$green10',
    success11: '$green11',
    success12: '$green12',
    // Success Alpha
    successA1: '$greenA1',
    successA2: '$greenA2',
    successA3: '$greenA3',
    successA4: '$greenA4',
    successA5: '$greenA5',
    successA6: '$greenA6',
    successA7: '$greenA7',
    successA8: '$greenA8',
    successA9: '$greenA9',
    successA10: '$greenA10',
    successA11: '$greenA11',
    successA12: '$greenA12',

    // Error
    error1: '$tomato1',
    error2: '$tomato2',
    error3: '$tomato3',
    error4: '$tomato4',
    error5: '$tomato5',
    error6: '$tomato6',
    error7: '$tomato7',
    error8: '$tomato8',
    error9: '$tomato9',
    error10: '$tomato10',
    error11: '$tomato11',
    error12: '$tomato12',
    // Error Alpha
    errorA1: '$tomatoA1',
    errorA2: '$tomatoA2',
    errorA3: '$tomatoA3',
    errorA4: '$tomatoA4',
    errorA5: '$tomatoA5',
    errorA6: '$tomatoA6',
    errorA7: '$tomatoA7',
    errorA8: '$tomatoA8',
    errorA9: '$tomatoA9',
    errorA10: '$tomatoA10',
    errorA11: '$tomatoA11',
    errorA12: '$tomatoA12',

    // Warning
    warning1: '$orange1',
    warning2: '$orange2',
    warning3: '$orange3',
    warning4: '$orange4',
    warning5: '$orange5',
    warning6: '$orange6',
    warning7: '$orange7',
    warning8: '$orange8',
    warning9: '$orange9',
    warning10: '$orange10',
    warning11: '$orange11',
    warning12: '$orange12',
    // Warning Alpha
    warningA1: '$orangeA1',
    warningA2: '$orangeA2',
    warningA3: '$orangeA3',
    warningA4: '$orangeA4',
    warningA5: '$orangeA5',
    warningA6: '$orangeA6',
    warningA7: '$orangeA7',
    warningA8: '$orangeA8',
    warningA9: '$orangeA9',
    warningA10: '$orangeA10',
    warningA11: '$orangeA11',
    warningA12: '$orangeA12'
  },

  dark: {
    ...darkColors,
    appBg: '$cyanA3',
    text: '$sage11',
    textContrast: '$sage12',

    // Neutral
    neutral1: '$sage1',
    neutral2: '$sage2',
    neutral3: '$sage3',
    neutral4: '$sage4',
    neutral5: '$sage5',
    neutral6: '$sage6',
    neutral7: '$sage7',
    neutral8: '$sage8',
    neutral9: '$sage9',
    neutral10: '$sage10',
    neutral11: '$sage11',
    neutral12: '$sage12',
    // Neutral Alpha
    neutralA1: '$sageA1',
    neutralA2: '$sageA2',
    neutralA3: '$sageA3',
    neutralA4: '$sageA4',
    neutralA5: '$sageA5',
    neutralA6: '$sageA6',
    neutralA7: '$sageA7',
    neutralA8: '$sageA8',
    neutralA9: '$sageA9',
    neutralA10: '$sageA10',
    neutralA11: '$sageA11',
    neutralA12: '$sageA12',

    // Info
    info1: '$mint1',
    info2: '$mint2',
    info3: '$mint3',
    info4: '$mint4',
    info5: '$mint5',
    info6: '$mint6',
    info7: '$mint7',
    info8: '$mint8',
    info9: '$mint9',
    info10: '$mint10',
    info11: '$mint11',
    info12: '$mint12',
    // Info Alpha
    infoA1: '$mintA1',
    infoA2: '$mintA2',
    infoA3: '$mintA3',
    infoA4: '$mintA4',
    infoA5: '$mintA5',
    infoA6: '$mintA6',
    infoA7: '$mintA7',
    infoA8: '$mintA8',
    infoA9: '$mintA9',
    infoA10: '$mintA10',
    infoA11: '$mintA11',
    infoA12: '$mintA12',

    // Success
    success1: '$lime1',
    success2: '$lime2',
    success3: '$lime3',
    success4: '$lime4',
    success5: '$lime5',
    success6: '$lime6',
    success7: '$lime7',
    success8: '$lime8',
    success9: '$lime9',
    success10: '$lime10',
    success11: '$lime11',
    success12: '$lime12',
    // Success Alpha
    successA1: '$limeA1',
    successA2: '$limeA2',
    successA3: '$limeA3',
    successA4: '$limeA4',
    successA5: '$limeA5',
    successA6: '$limeA6',
    successA7: '$limeA7',
    successA8: '$limeA8',
    successA9: '$limeA9',
    successA10: '$limeA10',
    successA11: '$limeA11',
    successA12: '$limeA12',

    // Error
    error1: '$tomato1',
    error2: '$tomato2',
    error3: '$tomato3',
    error4: '$tomato4',
    error5: '$tomato5',
    error6: '$tomato6',
    error7: '$tomato7',
    error8: '$tomato8',
    error9: '$tomato9',
    error10: '$tomato10',
    error11: '$tomato11',
    error12: '$tomato12',
    // Error Alpha
    errorA1: '$tomatoA1',
    errorA2: '$tomatoA2',
    errorA3: '$tomatoA3',
    errorA4: '$tomatoA4',
    errorA5: '$tomatoA5',
    errorA6: '$tomatoA6',
    errorA7: '$tomatoA7',
    errorA8: '$tomatoA8',
    errorA9: '$tomatoA9',
    errorA10: '$tomatoA10',
    errorA11: '$tomatoA11',
    errorA12: '$tomatoA12',

    // Warning
    warning1: '$amber1',
    warning2: '$amber2',
    warning3: '$amber3',
    warning4: '$amber4',
    warning5: '$amber5',
    warning6: '$amber6',
    warning7: '$amber7',
    warning8: '$amber8',
    warning9: '$amber9',
    warning10: '$amber10',
    warning11: '$amber11',
    warning12: '$amber12',
    // Warning Alpha
    warningA1: '$amberA1',
    warningA2: '$amberA2',
    warningA3: '$amberA3',
    warningA4: '$amberA4',
    warningA5: '$amberA5',
    warningA6: '$amberA6',
    warningA7: '$amberA7',
    warningA8: '$amberA8',
    warningA9: '$amberA9',
    warningA10: '$amberA10',
    warningA11: '$amberA11',
    warningA12: '$amberA12'
  }
};
